'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AsProctoredExam
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''lblCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCourse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''radioMidExists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioMidExists As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblMidStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMidStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMidEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMidEnd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkMidAvail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidAvail As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMIDLCLIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMIDLCLIP As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidDate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidDateClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidDateClear As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidCalendar As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''radioFinExists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioFinExists As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblFinStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFinEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinEnd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkFINAvail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFINAvail As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFINLCLIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFINLCLIP As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFinDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinDate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFinDateClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinDateClear As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFinCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinCalendar As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidAvailR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidAvailR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMIDRMTIPR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMIDRMTIPR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidDateR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidDateR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidDateClearR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidDateClearR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMidCalendarR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMidCalendarR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFINAvailR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFINAvailR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFINRMTIPR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFINRMTIPR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFinDateR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinDateR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFinDateClearR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinDateClearR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFinCalendarR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinCalendarR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblPageStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDateEntered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateEntered As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMasterStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CreateExamRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateExamRecord As Global.System.Web.UI.WebControls.Button
End Class
