'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Menu
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ckCourseInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCourseInfo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOther As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContent As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkToolsResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkToolsResources As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOther As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSetupGuide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSetupGuide As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtOtherMainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherMainMenu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCalendar As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCourseMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCourseMessage As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkQAForum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQAForum As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkBBResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBBResources As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMygrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMygrades As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMDCResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMDCResources As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCheckActivigy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCheckActivigy As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSyllabusStd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSyllabusStd As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSyllabusAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSyllabusAlign As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMenuGuide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMenuGuide As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkIntroVC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIntroVC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkVCOrientation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVCOrientation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkProcMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProcMenu As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkProcScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProcScript As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkProcPresent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProcPresent As Global.System.Web.UI.WebControls.CheckBox
End Class
