<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Textbook.aspx.vb" Inherits="RadDesigner.Textbook" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            font-size: medium;
        }
        .auto-style2 {
            font-size: x-large;
            font-family: Arial, Helvetica, sans-serif;
        }
        .auto-style3 {
            font-size: medium;
            color: #993333;
            font-family: Arial, Helvetica, sans-serif;
        }
        .auto-style4 {
            color: #993333;
            font-family: Arial, Helvetica, sans-serif;
        }
        .auto-style5 {
            font-family: Arial, Helvetica, sans-serif;
        }
        body {
    font-family: Arial, Helvetica, sans-serif;
}
        </style>
</head>
<body>
    <form id="form1" runat="server">
        <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server">
        </telerik:RadStyleSheetManager>
        <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
            <Scripts>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js">
                </asp:ScriptReference>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js">
                </asp:ScriptReference>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js">
                </asp:ScriptReference>
            </Scripts>
        </telerik:RadScriptManager>
        <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
        </telerik:RadAjaxManager>
        <div>
            <span class="auto-style2"><strong>Text Book for </strong></span><strong>
            <asp:Label ID="lblCourse" runat="server" CssClass="auto-style2"></asp:Label>
            </strong>
            <br />
            <span class="auto-style1"><span class="auto-style5">&nbsp;</span><span class="auto-style4">Please update and confirm for the </span></span>
            <asp:Label ID="lblUpcoming" runat="server" CssClass="auto-style3"></asp:Label>
            <span class="auto-style3">&nbsp;term.&nbsp; <asp:Button ID="Button1" runat="server" BackColor="#0099CC" ForeColor="White" Text="Add Textbook" Font-Bold="True" Font-Italic="True" Font-Size="Medium" />
            <br />
            .</span></div>
        <telerik:RadGrid ID="RadGrid1" runat="server" AutoGenerateColumns="False" AutoGenerateEditColumn="True" DataSourceID="SqlDataSource1" Skin="BlackMetroTouch" CellSpacing="-1" AllowAutomaticUpdates="True" BorderStyle="None" AllowAutomaticInserts="True" AllowSorting="True" AutoGenerateDeleteColumn="True" AllowAutomaticDeletes="True" ForeColor="White">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <AlternatingItemStyle ForeColor="White" />
            <MasterTableView DataKeyNames="ID" DataSourceID="SqlDataSource1" >
                <CommandItemSettings ShowExportToExcelButton="true" ShowAddNewRecordButton="true" ShowRefreshButton="false" />

             <Columns>
                    <telerik:GridBoundColumn DataField="ID" DataType="System.Int32" FilterControlAltText="Filter ID column" HeaderText="ID" ReadOnly="True" SortExpression="ID" UniqueName="ID" ColumnValidationSettings-RequiredFieldValidator-Visible="false" Visible ="false" >
<ColumnValidationSettings>
<RequiredFieldValidator Visible="False"></RequiredFieldValidator>
</ColumnValidationSettings>
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="CRS" DataType="System.Int32" FilterControlAltText="Filter CRS column" HeaderText="CRS" SortExpression="CRS" UniqueName="CRS" Visible ="false" >
                    </telerik:GridBoundColumn>
                    <telerik:GridCheckBoxColumn DataField="REQ" DataType="System.Boolean" FilterControlAltText="Filter REQ column" HeaderText="REQ" SortExpression="REQ" UniqueName="REQ">
                    </telerik:GridCheckBoxColumn>
                    <telerik:GridCheckBoxColumn DataField="SUP" DataType="System.Boolean" FilterControlAltText="Filter SUP column" HeaderText="SUP" SortExpression="SUP" UniqueName="SUP">
                    </telerik:GridCheckBoxColumn>
                    <telerik:GridCheckBoxColumn DataField="ALT" DataType="System.Boolean" FilterControlAltText="Filter ALT column" HeaderText="ALT" SortExpression="ALT" UniqueName="ALT">
                    </telerik:GridCheckBoxColumn>




                    <telerik:GridTemplateColumn HeaderText="Text_Title" ItemStyle-Width="300px" Visible="true">
                      <ItemTemplate>
                             <%#DataBinder.Eval(Container.DataItem, "Text_Title")%>
                      </ItemTemplate>

                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Text_Title") %>' width="1000" TextMode="MultiLine" Rows="2"></asp:TextBox>
                         </EditItemTemplate>

                       </telerik:GridTemplateColumn>


                    <telerik:GridBoundColumn DataField="Txt_ISBN" FilterControlAltText="Filter Txt_ISBN column" HeaderText="Txt_ISBN" SortExpression="Txt_ISBN" UniqueName="Txt_ISBN">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="EditionNo" FilterControlAltText="Filter EditionNo column" HeaderText="EditionNo" SortExpression="EditionNo" UniqueName="EditionNo">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="PUB_YYYY" FilterControlAltText="Filter PUB_YYYY column" HeaderText="PUB_YYYY" SortExpression="PUB_YYYY" UniqueName="PUB_YYYY">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Txt_Author" FilterControlAltText="Filter Txt_Author column" HeaderText="Txt_Author" SortExpression="Txt_Author" UniqueName="Txt_Author">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Txt_Publisher" FilterControlAltText="Filter Txt_Publisher column" HeaderText="Txt_Publisher" SortExpression="Txt_Publisher" UniqueName="Txt_Publisher">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Txt_Type" FilterControlAltText="Filter Txt_Type column" HeaderText="Txt_Type" SortExpression="Txt_Type" UniqueName="Txt_Type">
                    </telerik:GridBoundColumn>

                    <telerik:GridBoundColumn DataField="MasterCourse" FilterControlAltText="Filter MasterCourse column" HeaderText="MasterCourse" SortExpression="MasterCourse" UniqueName="MasterCourse">
                    </telerik:GridBoundColumn>

 

                </Columns>
            </MasterTableView>
            <EditItemStyle ForeColor="White" />
            <FooterStyle ForeColor="White" />
            <HeaderStyle ForeColor="White" />
            <CommandItemStyle ForeColor="White" />
            <ActiveItemStyle ForeColor="White" />
            <ItemStyle ForeColor="White" />
            <SelectedItemStyle ForeColor="White" />
        </telerik:RadGrid>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DesignConnectionString %>" DeleteCommand="DELETE FROM [OL_Textbooks] WHERE [ID] = @ID" InsertCommand="INSERT INTO [OL_Textbooks] ([CRS], [REQ], [SUP], [ALT], [Text_Title], [Txt_ISBN], [EditionNo], [PUB_YYYY], [Txt_Author], [Txt_Publisher], [Txt_Type], [MasterCourse]) VALUES (@CRS, @REQ, @SUP, @ALT, @Text_Title, @Txt_ISBN, @EditionNo, @PUB_YYYY, @Txt_Author, @Txt_Publisher, @Txt_Type, @MasterCourse)" SelectCommand="SELECT [ID], [CRS], [REQ], [SUP], [ALT], [Text_Title], [Txt_ISBN], [EditionNo], [PUB_YYYY], [Txt_Author], [Txt_Publisher], [Txt_Type], [MasterCourse] FROM [OL_Textbooks] WHERE ([MasterCourse] = @MasterCourse)" UpdateCommand="UPDATE [OL_Textbooks] SET [CRS] = @CRS, [REQ] = @REQ, [SUP] = @SUP, [ALT] = @ALT, [Text_Title] = @Text_Title, [Txt_ISBN] = @Txt_ISBN, [EditionNo] = @EditionNo, [PUB_YYYY] = @PUB_YYYY, [Txt_Author] = @Txt_Author, [Txt_Publisher] = @Txt_Publisher, [Txt_Type] = @Txt_Type, [MasterCourse] = @MasterCourse WHERE [ID] = @ID">
            <DeleteParameters>
                <asp:Parameter Name="ID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="CRS" Type="Int32" />
                <asp:Parameter Name="REQ" Type="Boolean" />
                <asp:Parameter Name="SUP" Type="Boolean" />
                <asp:Parameter Name="ALT" Type="Boolean" />
                <asp:Parameter Name="Text_Title" Type="String" />
                <asp:Parameter Name="Txt_ISBN" Type="String" />
                <asp:Parameter Name="EditionNo" Type="String" />
                <asp:Parameter Name="PUB_YYYY" Type="String" />
                <asp:Parameter Name="Txt_Author" Type="String" />
                <asp:Parameter Name="Txt_Publisher" Type="String" />
                <asp:Parameter Name="Txt_Type" Type="String" />
                <asp:Parameter Name="MasterCourse" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:SessionParameter DefaultValue="2185_ACG2011_MC_VC" Name="MasterCourse" SessionField="MasterCourse" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="CRS" Type="Int32" />
                <asp:Parameter Name="REQ" Type="Boolean" />
                <asp:Parameter Name="SUP" Type="Boolean" />
                <asp:Parameter Name="ALT" Type="Boolean" />
                <asp:Parameter Name="Text_Title" Type="String" />
                <asp:Parameter Name="Txt_ISBN" Type="String" />
                <asp:Parameter Name="EditionNo" Type="String" />
                <asp:Parameter Name="PUB_YYYY" Type="String" />
                <asp:Parameter Name="Txt_Author" Type="String" />
                <asp:Parameter Name="Txt_Publisher" Type="String" />
                <asp:Parameter Name="Txt_Type" Type="String" />
                <asp:Parameter Name="MasterCourse" Type="String" />
                <asp:Parameter Name="ID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:Label ID="lblStatus" runat="server" Font-Bold="True" ForeColor="#CC0000"></asp:Label>
        <br />
        <asp:Button ID="btnVerify" runat="server" BackColor="#00FF99" Text="Verify These Textbooks For This Master" />
    </form>
    <p>
        &nbsp;</p>
</body>
</html>
